// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MBS_MobileDirPad","status":true,"description":"This script creates a DirPad and a action button for touch\ndevices in order to make the movement better.\n<MBS MobileDirPad>","parameters":{"DPad Image":"./img/system/DirPad.png","ActionButton Image":"./img/system/ActionButton.png","CancelButton Image":"./img/system/CancelButton.png","Button Size":"40","DPad Position":"128; 452","ActionButton Position":"688; 452","CancelButton Position":"750; 64","Opacity":"200","Hide Duration":"15","PC Debug":"false","Only in Map":"true"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"TerraxLighting","status":true,"description":"v1.5.1 Creates an extra layer that darkens a map and adds lightsources!","parameters":{"Player radius":"300","Add to options":"Yes","Option menu entry":"Lighting effects","Reset Lights":"No","Save DaynightHours":"0","Save DaynightMinutes":"0","Save DaynightSeconds":"0","Flashlight offset":"0","Screensize X":"866","Screensize Y":"630","Kill Switch":"No"}}
];
